### ISSUE TITLE
Generation of Carriers

### ISSUE THREAD

**Issue by zylyz18** [dt-np/raser#67]
### After Chenxi changed the carrier distribution generated by the laser from two dimensions to three dimensions, two strange distributions of carriers appear in the center of the x - and y-axes. The carrier distribution is different than it was before. 

![63b152a9c8775a266d0727bc1f1508f](https://user-images.githubusercontent.com/80966977/134790653-11f1dc4b-3d7a-40b1-9e79-dff725cc6549.jpg)
![b203fa073b5579ac6e0b1edc5a7a108](https://user-images.githubusercontent.com/80966977/134790654-e29dbbef-d857-40f2-8fde-6f44a5da1669.jpg)

**Comment by heheda2001123** [comment]
![IMG_3994](https://user-images.githubusercontent.com/56708883/135042452-e00180af-8a14-400e-a541-bd6e64eeaa93.JPG)
Fixed.

**Comment by xshi** [comment]
Fixed in #68 .
